# Custom patterns for secret scanning
# This helps detect accidentally committed API keys and other secrets

patterns:
  - name: Gemini API Key
    pattern: 'API_KEY=AIza[0-9A-Za-z\\-_]{35}'
    severity: critical
    
  - name: YouTube API Key
    pattern: 'YOUTUBE_API_KEY=AIza[0-9A-Za-z\\-_]{35}'
    severity: critical
    
  - name: Generic API Key
    pattern: '(api_key|API_KEY|apikey|APIKEY)\\s*[:=]\\s*[\'"][0-9a-zA-Z]{32,}[\'"]'
    severity: high
